//! Connect 4 — interactive game using hooks + assembler-generated bytecode.
//!
//! All game logic (drop piece, switch player) runs as VM bytecode.
//! State via hooks:
//! - board: 7×6 grid in ZeroPage (42 cells × 4 bytes, 0=empty, 1=P1, 2=P2)
//! - current_player: Int bank (1 or 2)
//! - cursor_col: Int bank (0-6, column for auto-play demo)
//! - game_over: Int bank (0=playing, 1=won)
//! - move_counter: Int bank (counts ticks for auto-play timing)
//! - row_iter: Int bank (loop variable for scanning rows)

use matterstream_vm::hooks::HookContext;
use matterstream_vm::host::VmHost;
use matterstream_vm::rpn::RpnOp;
use matterstream_vm::ui_vm;
use matterstream_vm_asm::Asm;

const COLS: u32 = 7;
const ROWS: u32 = 6;
const CELL_SIZE: u32 = 80;
const BOARD_X: u32 = 40;
const BOARD_Y: u32 = 60;
const WIDTH: u32 = COLS * CELL_SIZE + BOARD_X * 2;
const HEIGHT: u32 = ROWS * CELL_SIZE + BOARD_Y + 80;

fn main() {
    // ── Hook allocation ──
    let mut hooks = HookContext::new();
    let board = hooks.use_state_grid(COLS * ROWS, 0);   // ZeroPage: 42 i32s = 168 bytes
    let current_player = hooks.use_state_i32(1);         // Int slot 0
    let cursor_col = hooks.use_state_i32(3);             // Int slot 1
    let game_over = hooks.use_state_i32(0);              // Int slot 2
    let move_counter = hooks.use_state_i32(0);           // Int slot 3
    let row_iter = hooks.use_state_i32(0);               // Int slot 4 (temp for row scanning)

    // ── Build logic bytecode ──
    let mut asm = Asm::new();

    let end = asm.def_label();
    let skip_move = asm.def_label();
    let drop_piece = asm.def_label();
    let drop_loop = asm.def_label();
    let drop_found = asm.def_label();
    let drop_full = asm.def_label();
    let switch_to_2 = asm.def_label();
    let after_switch = asm.def_label();

    // Check game_over
    asm.load(game_over);
    asm.push32(0);
    asm.cmp_ne();
    asm.jmp_if(end);

    // Increment move_counter
    asm.load(move_counter);
    asm.push32(1);
    asm.add();
    asm.store(move_counter);

    // Make a move every 30 ticks
    asm.load(move_counter);
    asm.push32(30);
    asm.mod_();
    asm.push32(1);
    asm.cmp_eq();
    asm.not();
    asm.jmp_if(skip_move);
    asm.jmp(drop_piece);

    asm.mark(skip_move);
    asm.jmp(end);

    // ── Drop piece subroutine ──
    // Uses row_iter as loop variable, cursor_col for column
    asm.mark(drop_piece);

    // row_iter = ROWS - 1 = 5 (start from bottom)
    asm.push32(ROWS - 1);
    asm.store(row_iter);

    asm.mark(drop_loop);

    // Compute ZeroPage address: board.index + (row_iter * COLS + cursor_col) * 4
    asm.load(row_iter);
    asm.push32(COLS);
    asm.mul();              // row * 7
    asm.load(cursor_col);
    asm.add();              // row * 7 + col
    asm.push32(4);
    asm.mul();              // (row * 7 + col) * 4
    asm.push32(board.index);
    asm.add();              // board.index + offset = ZP address

    // Load cell value at this address
    asm.dup();              // keep address for potential store
    asm.op(RpnOp::LoadZpI32);

    // If cell == 0, we found an empty slot
    asm.push32(0);
    asm.cmp_eq();
    asm.jmp_if(drop_found);

    // Not empty — drop the address copy, decrement row
    asm.drop_();            // drop the duplicate address

    asm.load(row_iter);
    asm.push32(1);
    asm.sub();
    asm.store(row_iter);

    // If row_iter < 0 (wraps to large u64), column is full
    asm.load(row_iter);
    asm.push32(ROWS);
    asm.cmp_ge();           // if row >= ROWS (wrapped unsigned), full
    asm.jmp_if(drop_full);

    asm.jmp(drop_loop);

    // ── Found empty cell — place piece ──
    asm.mark(drop_found);
    // Stack: [address]
    asm.load(current_player);  // [address, player]
    asm.swap();                // [player, address]
    asm.op(RpnOp::StoreZpI32); // store player at address

    // Switch player: 1→2, 2→1
    asm.load(current_player);
    asm.push32(1);
    asm.cmp_eq();
    asm.jmp_if(switch_to_2);

    // Was 2, set to 1
    asm.push32(1);
    asm.store(current_player);
    asm.jmp(after_switch);

    asm.mark(switch_to_2);
    asm.push32(2);
    asm.store(current_player);

    asm.mark(after_switch);

    // Advance cursor_col for demo: (col + 1) % 7
    asm.load(cursor_col);
    asm.push32(1);
    asm.add();
    asm.push32(COLS);
    asm.mod_();
    asm.store(cursor_col);
    asm.jmp(end);

    // Column full — just advance cursor
    asm.mark(drop_full);
    asm.load(cursor_col);
    asm.push32(1);
    asm.add();
    asm.push32(COLS);
    asm.mod_();
    asm.store(cursor_col);

    asm.mark(end);
    asm.halt();

    let output = asm.finish().expect("assembly failed");

    let render_bytecode = Vec::new();
    let mut host = VmHost::new(output.bytecode, render_bytecode, hooks);
    host.vm.string_table = output.string_table;

    let timeout_frames: Option<u64> = std::env::args()
        .position(|a| a == "--timeout")
        .and_then(|i| std::env::args().nth(i + 1))
        .and_then(|s| s.parse::<u64>().ok())
        .map(|secs| secs * 60);

    println!("Connect 4 — All game logic runs as VM bytecode");

    let mut frame = 0u64;
    let mut buf = vec![0u32; (WIDTH * HEIGHT) as usize];

    loop {
        frame += 1;
        if let Some(max) = timeout_frames {
            if frame > max {
                println!("Timeout reached after {} frames", frame);
                break;
            }
        }

        if let Err(e) = host.tick(16) {
            println!("VM error at frame {}: {}", frame, e);
            break;
        }

        // ── Render (CPU softbuffer path) ──
        for p in buf.iter_mut() {
            *p = 0x1a1a2e;
        }

        // Board background
        ui_vm::draw_filled_rect(
            &mut buf, WIDTH, HEIGHT,
            BOARD_X as i32, BOARD_Y as i32,
            COLS * CELL_SIZE, ROWS * CELL_SIZE,
            ui_vm::rgba(0, 0, 180, 255),
        );

        // Draw cells from ZeroPage
        for row in 0..ROWS {
            for col in 0..COLS {
                let cell_idx = (row * COLS + col) as usize;
                let zp_offset = board.index as usize + cell_idx * 4;
                let cell_val = if zp_offset + 3 < 256 {
                    i32::from_le_bytes([
                        host.vm.zero_page[zp_offset],
                        host.vm.zero_page[zp_offset + 1],
                        host.vm.zero_page[zp_offset + 2],
                        host.vm.zero_page[zp_offset + 3],
                    ])
                } else {
                    0
                };

                let cx = BOARD_X + col * CELL_SIZE + CELL_SIZE / 2;
                let cy = BOARD_Y + row * CELL_SIZE + CELL_SIZE / 2;

                let color = match cell_val {
                    1 => ui_vm::rgba(255, 50, 50, 255),
                    2 => ui_vm::rgba(255, 255, 50, 255),
                    _ => ui_vm::rgba(26, 26, 46, 255),
                };

                ui_vm::draw_filled_circle(&mut buf, WIDTH, HEIGHT, cx as i32, cy as i32, 30, color);
            }
        }

        if frame > 300 {
            break;
        }
    }

    let player = host.vm.int_bank[current_player.index as usize];
    println!("Connect 4 completed. {} frames, current player: {}", frame, player);
}
