//! Flappy Bird — physics-based game using hooks + assembler-generated bytecode.
//!
//! Physics (gravity, velocity, pipe movement, collision) all run as VM bytecode
//! using float opcodes (FAdd, FMul, FCmpGt, etc.).
//!
//! State via hooks:
//! - bird: Vec3 bank [x, y, velocity]
//! - pipe0/1/2: Vec4 bank [pipe_x, gap_y, scored, 0]
//! - score: Int bank
//! - game_state: Int bank (0=waiting, 1=playing, 2=dead)
//! - flap_timer: Int bank (auto-flap countdown)

use matterstream_vm::hooks::HookContext;
use matterstream_vm::host::VmHost;
use matterstream_vm::ui_vm;
use matterstream_vm_asm::Asm;

const WIDTH: u32 = 400;
const HEIGHT: u32 = 600;
const BIRD_X: f32 = 80.0;
const BIRD_RADIUS: u32 = 15;
const PIPE_WIDTH: f32 = 60.0;
const PIPE_GAP: f32 = 150.0;
const GRAVITY: f32 = 0.5;
const FLAP_VEL: f32 = -8.0;
const PIPE_SPEED: f32 = 2.5;
const GROUND_Y: f32 = 550.0;

fn main() {
    // ── Hook allocation ──
    let mut hooks = HookContext::new();
    let bird = hooks.use_state_vec3([BIRD_X, 300.0, 0.0]);       // Vec3 slot 0
    let pipe0 = hooks.use_state_vec4([400.0, 250.0, 0.0, 0.0]);  // Vec4 slot 0
    let pipe1 = hooks.use_state_vec4([600.0, 200.0, 0.0, 0.0]);  // Vec4 slot 1
    let pipe2 = hooks.use_state_vec4([800.0, 300.0, 0.0, 0.0]);  // Vec4 slot 2
    let score = hooks.use_state_i32(0);                            // Int slot 0
    let game_state = hooks.use_state_i32(1);                       // Int slot 1 (1=playing)
    let flap_timer = hooks.use_state_i32(0);                       // Int slot 2

    // ── Build logic bytecode using float opcodes ──
    let mut asm = Asm::new();

    let end = asm.def_label();
    let do_physics = asm.def_label();
    let no_flap = asm.def_label();
    let _pipe_loop_start = asm.def_label();
    let _pipe_done = asm.def_label();
    let _pipe_no_respawn = asm.def_label();
    let _pipe_no_score = asm.def_label();
    let _pipe_no_collision = asm.def_label();
    let _check_ground = asm.def_label();
    let dead = asm.def_label();

    // Check if game_state == 1 (playing)
    asm.load(game_state);
    asm.push32(1);
    asm.cmp_ne();
    asm.jmp_if(end);

    // ── Auto-flap timer ──
    asm.load(flap_timer);
    asm.push32(1);
    asm.add();
    asm.store(flap_timer);

    asm.load(flap_timer);
    asm.push32(25);
    asm.cmp_gt();
    asm.not();
    asm.jmp_if(no_flap);

    // Flap: set velocity to FLAP_VEL, reset timer
    asm.push_f32(FLAP_VEL);
    asm.store_bank_comp(bird, 2);  // bird.velocity = FLAP_VEL
    asm.push32(0);
    asm.store(flap_timer);

    asm.mark(no_flap);

    // ── Physics: velocity += gravity, y += velocity ──
    asm.mark(do_physics);

    // velocity += GRAVITY
    asm.load_bank_comp(bird, 2);   // bird.velocity
    asm.push_f32(GRAVITY);
    asm.fadd();
    asm.store_bank_comp(bird, 2);  // bird.velocity = velocity + gravity

    // y += velocity
    asm.load_bank_comp(bird, 1);   // bird.y
    asm.load_bank_comp(bird, 2);   // bird.velocity
    asm.fadd();
    asm.store_bank_comp(bird, 1);  // bird.y += velocity

    // ── Move pipes ──
    // Process each pipe (pipe0, pipe1, pipe2)
    // For each pipe: pipe.x -= PIPE_SPEED
    let pipes = [pipe0, pipe1, pipe2];
    for &pipe in &pipes {
        // pipe.x -= PIPE_SPEED
        asm.load_bank_comp(pipe, 0);
        asm.push_f32(PIPE_SPEED);
        asm.fsub();
        asm.store_bank_comp(pipe, 0);

        // Check if pipe off-screen left: pipe.x < -PIPE_WIDTH
        let no_respawn = asm.def_label();
        asm.load_bank_comp(pipe, 0);
        asm.push_f32(-PIPE_WIDTH);
        asm.fcmp_lt();
        asm.not();
        asm.jmp_if(no_respawn);

        // Respawn: pipe.x = WIDTH + 20, pipe.gap_y = random, pipe.scored = 0
        asm.push_f32(WIDTH as f32 + 20.0);
        asm.store_bank_comp(pipe, 0);

        // Random gap_y: use Rand opcode (100..400)
        asm.push32(300);
        asm.rand();
        asm.i2f();
        asm.push_f32(100.0);
        asm.fadd();
        asm.store_bank_comp(pipe, 1);

        // Reset scored flag
        asm.push_f32(0.0);
        asm.store_bank_comp(pipe, 2);

        asm.mark(no_respawn);

        // Check scoring: if pipe.x < BIRD_X and pipe.scored == 0
        let no_score = asm.def_label();
        asm.load_bank_comp(pipe, 0);
        asm.push_f32(BIRD_X);
        asm.fcmp_lt();
        asm.not();
        asm.jmp_if(no_score);

        asm.load_bank_comp(pipe, 2);
        asm.push_f32(0.0);
        asm.fcmp_eq();
        asm.not();
        asm.jmp_if(no_score);

        // Score!
        asm.push_f32(1.0);
        asm.store_bank_comp(pipe, 2);  // mark scored
        asm.load(score);
        asm.push32(1);
        asm.add();
        asm.store(score);

        asm.mark(no_score);

        // ── Collision detection ──
        let no_coll = asm.def_label();
        let bird_r = BIRD_RADIUS as f32;

        // Check horizontal overlap: bird_x + r > pipe.x && bird_x - r < pipe.x + PIPE_WIDTH
        asm.push_f32(BIRD_X + bird_r);
        asm.load_bank_comp(pipe, 0);
        asm.fcmp_gt();
        asm.not();
        asm.jmp_if(no_coll);

        asm.push_f32(BIRD_X - bird_r);
        asm.load_bank_comp(pipe, 0);
        asm.push_f32(PIPE_WIDTH);
        asm.fadd();
        asm.fcmp_lt();
        asm.not();
        asm.jmp_if(no_coll);

        // Check vertical gap: bird_y - r < gap_y - GAP/2 || bird_y + r > gap_y + GAP/2
        let _gap_ok = asm.def_label();

        // bird_y - r < gap_y - GAP/2 ?
        asm.load_bank_comp(bird, 1);
        asm.push_f32(bird_r);
        asm.fsub();                     // bird_y - r
        asm.load_bank_comp(pipe, 1);
        asm.push_f32(PIPE_GAP / 2.0);
        asm.fsub();                     // gap_y - GAP/2
        asm.fcmp_lt();
        asm.jmp_if(dead);

        // bird_y + r > gap_y + GAP/2 ?
        asm.load_bank_comp(bird, 1);
        asm.push_f32(bird_r);
        asm.fadd();                     // bird_y + r
        asm.load_bank_comp(pipe, 1);
        asm.push_f32(PIPE_GAP / 2.0);
        asm.fadd();                     // gap_y + GAP/2
        asm.fcmp_gt();
        asm.jmp_if(dead);

        asm.mark(no_coll);
    }

    // ── Ground/ceiling collision ──
    // if bird_y < 0 || bird_y > GROUND_Y → dead
    asm.load_bank_comp(bird, 1);
    asm.push_f32(0.0);
    asm.fcmp_lt();
    asm.jmp_if(dead);

    asm.load_bank_comp(bird, 1);
    asm.push_f32(GROUND_Y);
    asm.fcmp_gt();
    asm.jmp_if(dead);

    asm.jmp(end);

    // ── Dead state ──
    asm.mark(dead);
    asm.push32(2);
    asm.store(game_state);

    asm.mark(end);
    asm.halt();

    let output = asm.finish().expect("assembly failed");

    let render_bytecode = Vec::new();
    let mut host = VmHost::new(output.bytecode, render_bytecode, hooks);
    host.vm.string_table = output.string_table;

    // Initialize bird and pipe state in VM banks
    host.vm.vec3_bank[bird.index as usize] = [BIRD_X, 300.0, 0.0];
    host.vm.vec4_bank[pipe0.index as usize] = [400.0, 250.0, 0.0, 0.0];
    host.vm.vec4_bank[pipe1.index as usize] = [600.0, 200.0, 0.0, 0.0];
    host.vm.vec4_bank[pipe2.index as usize] = [800.0, 300.0, 0.0, 0.0];
    host.vm.int_bank[game_state.index as usize] = 1;

    let timeout_frames: Option<u64> = std::env::args()
        .position(|a| a == "--timeout")
        .and_then(|i| std::env::args().nth(i + 1))
        .and_then(|s| s.parse::<u64>().ok())
        .map(|secs| secs * 60);

    println!("Flappy Bird — Physics runs as VM bytecode with float opcodes");

    let mut buf = vec![0u32; (WIDTH * HEIGHT) as usize];
    let mut frame = 0u64;

    loop {
        frame += 1;
        if let Some(max) = timeout_frames {
            if frame > max {
                println!("Timeout reached after {} frames", frame);
                break;
            }
        }

        let state = host.vm.int_bank[game_state.index as usize];
        if state == 2 {
            break;
        }

        if let Err(e) = host.tick(16) {
            println!("VM error at frame {}: {}", frame, e);
            break;
        }

        // ── Render ──
        for p in buf.iter_mut() {
            *p = 0x70C5CE;
        }

        // Ground
        ui_vm::draw_filled_rect(
            &mut buf, WIDTH, HEIGHT,
            0, GROUND_Y as i32, WIDTH, HEIGHT - GROUND_Y as u32,
            ui_vm::rgba(222, 184, 135, 255),
        );

        // Pipes
        let pipe_indices = [pipe0.index, pipe1.index, pipe2.index];
        for &pi in &pipe_indices {
            let pipe = host.vm.vec4_bank[pi as usize];
            let px = pipe[0] as i32;
            let gap_y = pipe[1];
            let pipe_color = ui_vm::rgba(50, 200, 50, 255);

            let top_h = (gap_y - PIPE_GAP / 2.0) as u32;
            if top_h > 0 {
                ui_vm::draw_filled_rect(
                    &mut buf, WIDTH, HEIGHT,
                    px, 0, PIPE_WIDTH as u32, top_h,
                    pipe_color,
                );
            }

            let bottom_y = (gap_y + PIPE_GAP / 2.0) as i32;
            let bottom_h = GROUND_Y as i32 - bottom_y;
            if bottom_h > 0 {
                ui_vm::draw_filled_rect(
                    &mut buf, WIDTH, HEIGHT,
                    px, bottom_y, PIPE_WIDTH as u32, bottom_h as u32,
                    pipe_color,
                );
            }
        }

        // Bird
        let bird_data = host.vm.vec3_bank[bird.index as usize];
        ui_vm::draw_filled_circle(
            &mut buf, WIDTH, HEIGHT,
            bird_data[0] as i32, bird_data[1] as i32,
            BIRD_RADIUS,
            ui_vm::rgba(255, 255, 0, 255),
        );

        if frame > 600 {
            break;
        }
    }

    let final_score = host.vm.int_bank[score.index as usize];
    println!(
        "Flappy Bird completed. {} frames, score: {}",
        frame, final_score
    );
}
