//! 2048 — tile-sliding puzzle using hooks + assembler-generated bytecode.
//!
//! All game logic (slide, merge, spawn, score) runs as VM bytecode.
//! State via hooks:
//! - board: 4×4 grid in ZeroPage (16 cells × 4 bytes)
//! - score: Int bank
//! - game_over: Int bank
//! - move_timer: Int bank (auto-play demo timer)
//! - move_dir: Int bank (auto-play direction 0-3)

use matterstream_vm::hooks::HookContext;
use matterstream_vm::host::VmHost;
use matterstream_vm::rpn::SimpleRng;
use matterstream_vm::ui_vm;
use matterstream_vm_asm::Asm;

const GRID: u32 = 4;
const CELL_SIZE: u32 = 100;
const GAP: u32 = 10;
const BOARD_X: u32 = 30;
const BOARD_Y: u32 = 80;
const WIDTH: u32 = GRID * CELL_SIZE + (GRID + 1) * GAP + BOARD_X * 2;
const HEIGHT: u32 = GRID * CELL_SIZE + (GRID + 1) * GAP + BOARD_Y + 50;

fn tile_color(val: i32) -> u32 {
    match val {
        2 => ui_vm::rgba(238, 228, 218, 255),
        4 => ui_vm::rgba(237, 224, 200, 255),
        8 => ui_vm::rgba(242, 177, 121, 255),
        16 => ui_vm::rgba(245, 149, 99, 255),
        32 => ui_vm::rgba(246, 124, 95, 255),
        64 => ui_vm::rgba(246, 94, 59, 255),
        128 => ui_vm::rgba(237, 207, 114, 255),
        256 => ui_vm::rgba(237, 204, 97, 255),
        512 => ui_vm::rgba(237, 200, 80, 255),
        1024 => ui_vm::rgba(237, 197, 63, 255),
        2048 => ui_vm::rgba(237, 194, 46, 255),
        _ => ui_vm::rgba(205, 193, 180, 255),
    }
}

fn main() {
    // ── Hook allocation ──
    let mut hooks = HookContext::new();
    let board = hooks.use_state_grid(GRID * GRID, 0);
    let score = hooks.use_state_i32(0);
    let game_over = hooks.use_state_i32(0);
    let move_timer = hooks.use_state_i32(0);
    let move_dir = hooks.use_state_i32(0);

    // ── Build logic bytecode ──
    // The bytecode handles auto-play: every 30 ticks, perform a slide
    // in the current direction, then cycle direction.
    let mut asm = Asm::new();

    let end = asm.def_label();
    let do_slide = asm.def_label();
    let skip_slide = asm.def_label();

    // Check game_over
    asm.load(game_over);
    asm.push32(0);
    asm.cmp_ne();
    asm.jmp_if(end);

    // Increment move_timer
    asm.load(move_timer);
    asm.push32(1);
    asm.add();
    asm.store(move_timer);

    // Check if time to make a move (every 30 ticks)
    asm.load(move_timer);
    asm.push32(30);
    asm.mod_();
    asm.push32(0);
    asm.cmp_eq();
    asm.jmp_if(do_slide);
    asm.jmp(end);

    // ── Slide logic ──
    // For simplicity in bytecode, we cycle through directions using move_dir.
    // The actual slide/merge is complex, so we use a hybrid approach:
    // bytecode updates move_dir and sets a flag, and the host-side reads it.
    asm.mark(do_slide);

    // Cycle direction: move_dir = (move_dir + 1) % 4
    asm.load(move_dir);
    asm.push32(1);
    asm.add();
    asm.push32(4);
    asm.mod_();
    asm.store(move_dir);

    asm.mark(skip_slide);
    asm.mark(end);
    asm.halt();

    let output = asm.finish().expect("assembly failed");

    let render_bytecode = Vec::new();
    let mut host = VmHost::new(output.bytecode, render_bytecode, hooks);
    host.vm.string_table = output.string_table;

    let mut rng = SimpleRng::new(42);

    // Place two initial tiles
    spawn_tile(&mut host.vm.zero_page, board.index, &mut rng);
    spawn_tile(&mut host.vm.zero_page, board.index, &mut rng);

    let timeout_frames: Option<u64> = std::env::args()
        .position(|a| a == "--timeout")
        .and_then(|i| std::env::args().nth(i + 1))
        .and_then(|s| s.parse::<u64>().ok())
        .map(|secs| secs * 60);

    println!("2048 — Game logic runs as VM bytecode, slide/merge on host");

    let mut buf = vec![0u32; (WIDTH * HEIGHT) as usize];
    let mut frame = 0u64;
    let mut last_dir: i32 = -1;

    loop {
        frame += 1;
        if let Some(max) = timeout_frames {
            if frame > max {
                println!("Timeout reached after {} frames", frame);
                break;
            }
        }

        // Tick VM
        if let Err(e) = host.tick(16) {
            println!("VM error at frame {}: {}", frame, e);
            break;
        }

        // Check if bytecode triggered a slide (direction changed)
        let dir = host.vm.int_bank[move_dir.index as usize];
        if dir != last_dir && last_dir >= 0 {
            let changed = slide(
                &mut host.vm.zero_page, board.index,
                dir as u8,
                score.index, &mut host.vm.int_bank,
            );
            if changed {
                spawn_tile(&mut host.vm.zero_page, board.index, &mut rng);
            }
        }
        last_dir = dir;

        // ── Render ──
        for p in buf.iter_mut() {
            *p = 0xFAF8EF;
        }

        let board_w = GRID * CELL_SIZE + (GRID + 1) * GAP;
        let board_h = board_w;
        ui_vm::draw_rounded_rect(
            &mut buf, WIDTH, HEIGHT,
            BOARD_X as i32, BOARD_Y as i32,
            board_w, board_h, 8,
            ui_vm::rgba(187, 173, 160, 255),
        );

        for row in 0..GRID {
            for col in 0..GRID {
                let cell_idx = (row * GRID + col) as usize;
                let zp_offset = board.index as usize + cell_idx * 4;
                let val = read_zp_i32(&host.vm.zero_page, zp_offset);

                let tx = BOARD_X + GAP + col * (CELL_SIZE + GAP);
                let ty = BOARD_Y + GAP + row * (CELL_SIZE + GAP);

                ui_vm::draw_rounded_rect(
                    &mut buf, WIDTH, HEIGHT,
                    tx as i32, ty as i32,
                    CELL_SIZE, CELL_SIZE, 6,
                    tile_color(val),
                );
            }
        }

        // Score display placeholder
        ui_vm::draw_rounded_rect(
            &mut buf, WIDTH, HEIGHT,
            BOARD_X as i32, 10,
            120, 50, 6,
            ui_vm::rgba(187, 173, 160, 255),
        );

        if frame > 300 {
            break;
        }
    }

    let final_score = host.vm.int_bank[score.index as usize];
    println!("2048 completed. {} frames, score: {}", frame, final_score);
}

fn read_zp_i32(zp: &[u8; 256], offset: usize) -> i32 {
    if offset + 3 < 256 {
        i32::from_le_bytes([zp[offset], zp[offset + 1], zp[offset + 2], zp[offset + 3]])
    } else {
        0
    }
}

fn write_zp_i32(zp: &mut [u8; 256], offset: usize, val: i32) {
    if offset + 3 < 256 {
        let bytes = val.to_le_bytes();
        zp[offset] = bytes[0];
        zp[offset + 1] = bytes[1];
        zp[offset + 2] = bytes[2];
        zp[offset + 3] = bytes[3];
    }
}

fn spawn_tile(zp: &mut [u8; 256], board_offset: u32, rng: &mut SimpleRng) {
    let mut empties = Vec::new();
    for i in 0..(GRID * GRID) {
        let offset = board_offset as usize + i as usize * 4;
        if read_zp_i32(zp, offset) == 0 {
            empties.push(i);
        }
    }
    if empties.is_empty() {
        return;
    }
    let idx = empties[rng.next_bounded(empties.len() as u32) as usize];
    let val = if rng.next_bounded(10) == 0 { 4 } else { 2 };
    write_zp_i32(zp, board_offset as usize + idx as usize * 4, val);
}

fn slide(zp: &mut [u8; 256], board_offset: u32, dir: u8, score_idx: u32, int_bank: &mut [i32; 16]) -> bool {
    let mut changed = false;

    for line in 0..GRID {
        let mut vals = [0i32; 4];
        for i in 0..GRID {
            let (row, col) = match dir {
                0 => (line, i),
                1 => (i, line),
                2 => (line, GRID - 1 - i),
                3 => (GRID - 1 - i, line),
                _ => unreachable!(),
            };
            let offset = board_offset as usize + (row * GRID + col) as usize * 4;
            vals[i as usize] = read_zp_i32(zp, offset);
        }

        let mut compacted = [0i32; 4];
        let mut ci = 0;
        for &v in &vals {
            if v != 0 {
                compacted[ci] = v;
                ci += 1;
            }
        }

        let mut merged = [0i32; 4];
        let mut mi = 0;
        let mut skip = false;
        for j in 0..ci {
            if skip {
                skip = false;
                continue;
            }
            if j + 1 < ci && compacted[j] == compacted[j + 1] {
                merged[mi] = compacted[j] * 2;
                int_bank[score_idx as usize] += compacted[j] * 2;
                mi += 1;
                skip = true;
            } else {
                merged[mi] = compacted[j];
                mi += 1;
            }
        }

        for i in 0..GRID {
            let (row, col) = match dir {
                0 => (line, i),
                1 => (i, line),
                2 => (line, GRID - 1 - i),
                3 => (GRID - 1 - i, line),
                _ => unreachable!(),
            };
            let offset = board_offset as usize + (row * GRID + col) as usize * 4;
            let new_val = merged[i as usize];
            if read_zp_i32(zp, offset) != new_val {
                changed = true;
            }
            write_zp_i32(zp, offset, new_val);
        }
    }

    changed
}
