//! matterstream-compiler
//!
//! This crate provides the `Compiler` responsible for parsing TSX (TypeScript XML)
//! source code and transforming it into a sequence of `CompiledOps`.
//! It acts as the initial translation layer, converting high-level UI descriptions
//! into a low-level, executable intermediate representation.

use oxc_allocator::Allocator;
use oxc_parser::Parser;
use oxc_span::SourceType;
use oxc_ast::{visit::{self, Visit}, ast::*};
use oxc_syntax::operator::UnaryOperator;
use anyhow::{Result, anyhow};

use matterstream_core::{Op, Primitive, OpsHeader, CompiledOps};

/// A type alias for `Result` with `CompilerError` as the error type.
pub type CompilerResult<T> = Result<T>;
/// The error type for the `matterstream-compiler` crate, utilizing `anyhow::Error`.
pub type CompilerError = anyhow::Error;

/// The main compiler for MatterStream UI definitions.
///
/// This compiler takes TSX source code, parses it using `oxc_parser`,
/// and traverses the resulting AST to generate a sequence of `CompiledOps`.
pub struct Compiler;

impl Compiler {
    /// Compiles a given TSX source string into `CompiledOps`.
    ///
    /// This function performs the following steps:
    /// 1. Initializes an `oxc_parser` to parse the TSX input.
    /// 2. Handles any parsing errors by collecting them into a single error string.
    /// 3. Creates a `MatterStreamVisitor` to traverse the AST and generate MatterStream `Op`s.
    /// 4. Wraps the generated `Op`s in a `CompiledOps` structure.
    ///
    /// # Arguments
    ///
    /// * `source_text` - A string slice containing the TSX source code.
    ///
    /// # Returns
    ///
    /// A `CompilerResult` containing `CompiledOps` on success,
    /// or a `CompilerError` if compilation fails (e.g., due to syntax errors).
    pub fn compile(source_text: &str) -> CompilerResult<CompiledOps> {
        // Backwards-compatible entry: create a new Binder and call compile_with_binder
        let binder = std::sync::Arc::new(matterstream_core::Binder::new());
        Self::compile_with_binder(source_text, binder)
    }

    /// Compile with an externally-provided Binder instance (shared across parser/processor/compiler)
    pub fn compile_with_binder(source_text: &str, _binder: std::sync::Arc<matterstream_core::Binder>) -> CompilerResult<CompiledOps> {
        let allocator = Allocator::default();
        let source_type = SourceType::from_path("example.tsx").unwrap();
        let ret = Parser::new(&allocator, source_text, source_type).parse();

        if !ret.errors.is_empty() {
            let error_messages: Vec<String> = ret.errors
                .into_iter()
                .map(|e| format!("{:?}", e))
                .collect();
            return Err(anyhow!(error_messages.join("\n")));
        }

        let mut visitor = MatterStreamVisitor::new_with_binder(_binder);
        visitor.visit_program(&ret.program);

        let header = OpsHeader::new(vec![], false);

        Ok(CompiledOps::new(header, visitor.ops))
    }
}

/// A visitor that traverses the TSX AST generated by `oxc_parser`
/// and translates relevant JSX elements into MatterStream `Op`s.
struct MatterStreamVisitor {
    /// The accumulated list of MatterStream operations.
    ops: Vec<Op>,
    /// Optional binder for resolving imported/bound components
    binder: Option<std::sync::Arc<matterstream_core::Binder>>,
}

impl MatterStreamVisitor {
    /// Creates a new, default instance of `MatterStreamVisitor` without a binder.
    fn new() -> Self {
        Self { ops: Vec::new(), binder: None }
    }

    /// Creates a new visitor that shares the provided Binder.
    fn new_with_binder(binder: std::sync::Arc<matterstream_core::Binder>) -> Self {
        Self { ops: Vec::new(), binder: Some(binder) }
    }

    /// Parses an RGBA hex string (e.g., "#RRGGBBAA") into an array of `f32` components.
    ///
    /// # Arguments
    ///
    /// * `hex` - The RGBA hex string.
    ///
    /// # Returns
    ///
    /// An `Option` containing `[f32; 4]` if parsing is successful, otherwise `None`.
    fn parse_rgba_hex(hex: &str) -> Option<[f32; 4]> {
        if hex.len() != 9 || !hex.starts_with('#') {
            return None;
        }

        let r = u8::from_str_radix(&hex[1..3], 16).ok()?;
        let g = u8::from_str_radix(&hex[3..5], 16).ok()?;
        let b = u8::from_str_radix(&hex[5..7], 16).ok()?;
        let a = u8::from_str_radix(&hex[7..9], 16).ok()?;

        Some([
            r as f32 / 255.0,
            g as f32 / 255.0,
            b as f32 / 255.0,
            a as f32 / 255.0,
        ])
    }
}

impl<'a> Visit<'a> for MatterStreamVisitor {
    /// Visits a JSX element in the AST.
    ///
    /// This method specifically looks for `<Slab>` elements and extracts
    /// their `x`, `y`, and `color` attributes to generate corresponding
    /// MatterStream `Op`s.
    ///
    /// # Arguments
    ///
    /// * `element` - The `JSXElement` to visit.
    fn visit_jsx_element(&mut self, element: &JSXElement<'a>) {
        if let JSXElementName::Identifier(ident) = &element.opening_element.name {
            // Determine if this identifier refers to a bound functional component
            let is_builtin = ident.name == "Slab" || ident.name == "Text";
            let is_component = if let Some(binder) = &self.binder {
                binder.get_handle(&ident.name).is_some() || is_builtin
            } else {
                is_builtin
            };
            if is_component {
                let mut x_val = 0.0;
                let mut y_val = 0.0;
                let mut color_val: Option<[f32; 4]> = None;
                let mut label_val: Option<String> = None;

                for attribute in &element.opening_element.attributes {
                    if let JSXAttributeItem::Attribute(attr) = attribute {
                        if let JSXAttributeName::Identifier(name) = &attr.name {
                            if name.name == "x" {
                                if let Some(JSXAttributeValue::ExpressionContainer(container)) = &attr.value {
                                    if let JSXExpression::NumericLiteral(num_literal) = &container.expression {
                                        x_val = num_literal.value as f32;
                                    } else if let JSXExpression::UnaryExpression(unary) = &container.expression {
                                        if unary.operator == UnaryOperator::UnaryNegation {
                                            if let Expression::NumericLiteral(lit) = &unary.argument {
                                                x_val = -(lit.value as f32);
                                            }
                                        }
                                    }
                                }
                            } else if name.name == "y" {
                                if let Some(JSXAttributeValue::ExpressionContainer(container)) = &attr.value {
                                    if let JSXExpression::NumericLiteral(num_literal) = &container.expression {
                                        y_val = num_literal.value as f32;
                                    } else if let JSXExpression::UnaryExpression(unary) = &container.expression {
                                        if unary.operator == UnaryOperator::UnaryNegation {
                                            if let Expression::NumericLiteral(lit) = &unary.argument {
                                                y_val = -(lit.value as f32);
                                            }
                                        }
                                    }
                                }
                            } else if name.name == "label" {
                                if let Some(JSXAttributeValue::StringLiteral(str_literal)) = &attr.value {
                                    label_val = Some(str_literal.value.to_string());
                                } else if let Some(JSXAttributeValue::ExpressionContainer(container)) = &attr.value {
                                    if let JSXExpression::StringLiteral(str_literal) = &container.expression {
                                        label_val = Some(str_literal.value.to_string());
                                    }
                                }
                            } else if name.name == "color" {
                                let color_string_option = if let Some(JSXAttributeValue::StringLiteral(str_literal)) = &attr.value {
                                    Some(&str_literal.value)
                                } else if let Some(JSXAttributeValue::ExpressionContainer(container)) = &attr.value {
                                    if let JSXExpression::StringLiteral(str_literal) = &container.expression {
                                        Some(&str_literal.value)
                                    } else {
                                        None
                                    }
                                } else {
                                    None
                                };

                                if let Some(color_str) = color_string_option {
                                    if let Some(parsed_color) = Self::parse_rgba_hex(color_str) {
                                        color_val = Some(parsed_color);
                                    } else {
                                        eprintln!("Warning: 'color' attribute has invalid hex format '{}'. Defaulting to white.", color_str);
                                    }
                                } else {
                                    eprintln!("Warning: 'color' attribute is not a valid string literal or expression container. Defaulting to white.");
                                }
                            }
                        }
                    }
                }

                if let Some(color) = color_val {
                    self.ops.push(Op::SetColor(color));
                } else {
                    self.ops.push(Op::SetColor([1.0, 1.0, 1.0, 1.0]));
                }
                let primitive = match ident.name.as_str() {
                    "Text" => Primitive::Text,
                    _ => Primitive::Slab,
                };
                if let Some(label) = label_val {
                    self.ops.push(Op::SetLabel(label));
                }
                self.ops.push(Op::SetTrans([x_val, y_val, 0.0]));
                self.ops.push(Op::Draw { primitive, position_rsi: 0 });
            }
        }

        visit::walk::walk_jsx_element(self, element);
    }
}
